@Suppress("unused")
object Dependencies {
    const val android_gradlePlugin = "com.android.tools.build:gradle:8.11.1"
    const val androidx_activity_compose = "androidx.activity:activity-compose:1.9.3"
    const val androidx_core_ktx = "androidx.core:core-ktx:1.13.1"
    const val atomicFu_gradlePlugin = "org.jetbrains.kotlinx:atomicfu-gradle-plugin:0.29.0"
    const val compose_gradlePlugin = "org.jetbrains.compose:compose-gradle-plugin:1.8.2"
    const val compose_hotReload_gradlePlugin = "org.jetbrains.compose.hot-reload:hot-reload-gradle-plugin:1.0.0-beta06"
    const val coroutines_android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.1"
    const val coroutines_core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.1"
    const val coroutines_swing = "org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.10.1"
    const val coroutines_test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.1"
    const val evas = "io.sellmair:evas:1.3.0"
    const val evas_compose = "io.sellmair:evas-compose:1.3.0"
    const val kotlin_composeCompilerPlugin = "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.2.0"
    const val kotlin_gradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.0"
    const val kotlinx_collections_immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.4.0"
    const val kotlinx_datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1"
    const val multiplatform_settings = "com.russhwolf:multiplatform-settings:1.3.0"
    const val okio = "com.squareup.okio:okio:3.10.2"
    const val sqldelight_androidDriver = "app.cash.sqldelight:android-driver:2.1.0"
    const val sqldelight_coroutineExtensions = "app.cash.sqldelight:coroutines-extensions:2.1.0"
    const val sqldelight_gradlePlugin = "app.cash.sqldelight:gradle-plugin:2.1.0"
    const val sqldelight_nativeDriver = "app.cash.sqldelight:native-driver:2.1.0"
    const val sqldelight_sqliteDriver = "app.cash.sqldelight:sqlite-driver:2.1.0"
}
